Feat/reward liquid assets
elys-network/financial-snapshot-contract pull request #2
Opened 2023-10-09 09:15 UTC by kenta-elys

- Add rewards, liquid assets & liquid asset endpoints and states and types.

2023-10-09 09:45 UTC, politeWall requested changes

2023-10-09 09:45 UTC, politeWall commented on .vscode/settings.json
.vscode is in the gitignore and should not be there

2023-10-09 09:45 UTC, politeWall commented on src/error.rs
>      #[error("{sender} is not the owner of the order")]
the Unauthorized error is not used in the contract

2023-10-09 09:45 UTC, politeWall commented on src/action/query/get_liquid_asset.rs
> +            None => LiquidAsset::new_dummy(),
why do you return a new_dummy instead of returning  the error `LiquidAssetNotFound`

2023-10-12 09:30 UTC, politeWall commented on .vscode/settings.json
Why is there a .vscode directory if it's in the .gitignore?

2023-10-16 09:24 UTC, cosmic-vagabond approved these changes

2023-10-16 09:29 UTC, politeWall approved these changes

2023-10-16 09:40 UTC, merged